version: '2'

services:
  master:
    build: ./jmeter-master
    container_name: master
    tty: true
    networks:
      - jmeter-network
  slave:
    build: ./jmeter-slave
    networks:
      - jmeter-network

networks:
  jmeter-network:
    driver: bridge